CREATE TABLE IF NOT EXISTS links (
id SERIAL PRIMARY KEY,
code VARCHAR(8) NOT NULL UNIQUE,
target_url TEXT NOT NULL,
total_clicks INTEGER NOT NULL DEFAULT 0,
last_clicked TIMESTAMP WITH TIME ZONE,
created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);


CREATE INDEX IF NOT EXISTS idx_links_code ON links(code);